version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2004:202111-02

commands:
  build:
    description: Install dependencies and build the project
    steps:
      - run:
          name: Use NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Use Node LTS
          command: |
            nvm install 'lts/*'
            nvm use 'lts/*'
            nvm alias default 'lts/*'
      - run:
          name: Install exact dependencies
          command: npm ci
      - run:
          name: Build the website
          command: npm run build

jobs:
  build-and-test:
    executor: linux
    steps:
      - checkout
      - build

  build-test-and-deploy:
    executor: linux
    steps:
      - checkout
      - build
      - run:
          name: Pack the website in a .tar.gz
          command: tar czf static_website.tar.gz -C dist .
      - store_artifacts:
          path: static_website.tar.gz
      - run:
          name: Trigger a deploy of the deploy project passing the desired environment/location to deploy to
          command: |
            curl -H 'Content-Type: application/json' -H "Circle-Token: $CIRCLECI_API_TOKEN_NARAMSIM" --data "{\"branch\":\"master\",\"parameters\":{\"deploy_location\":\"$CIRCLE_BRANCH\"}}" -X POST https://circleci.com/api/v2/project/github/PokeAPI/deploy/pipeline

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test
      - build-test-and-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
  weekly:
    jobs:
      - build-and-test
      - build-test-and-deploy:
          requires:
            - build-and-test
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - staging
