version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-1604:201903-01

commands:
  build:
    description: Install dependencies and build the project
    steps:
      - run:
          name: Use NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Use Node 12
          command: |
            nvm use v12
            nvm alias default v12
      - run:
          name: Install exact dependencies
          command: npm ci
      - run:
          name: Build the website
          command: npm run build

jobs:
  build-and-test:
    executor: linux
    steps:
      - checkout
      - build

  build-test-and-deploy:
    executor: linux
    steps:
      - checkout
      - build
      - run:
          name: Pack the website in a .tar.gz
          command: tar czf static_website.tar.gz -C dist .
      - store_artifacts:
          path: static_website.tar.gz
      - run:
          name: Trigger a deploy of the deploy project passing the desired environment/location to deploy to
          command: 'curl --header "Content-Type: application/json" --data "{\"build_parameters\": {\"deploy_location\": \"$CIRCLE_BRANCH\", \"CIRCLE_JOB\": \"deploy\"}}" --request POST "https://circleci.com/api/v1.1/project/github/PokeAPI/deploy/tree/master?circle-token=$CIRCLECI_API_TOKEN"'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test
      - build-test-and-deploy:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only:
                - staging
  weekly:
    jobs:
      - build-and-test
      - build-test-and-deploy:
          requires:
            - build-and-test
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - staging
