version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.11.0

jobs:
  build-and-test-and-deploy:
    <<: *defaults
    steps:
    - checkout
    - run: npm install -E
    - run: npm run build
    - run: tar czf static_website.tar.gz -C dist .
    - store_artifacts:
        path: static_website.tar.gz

    # Trigger a new build of the deploy project
    - run: "curl -X POST --header \"Content-Type: application/json\" https://circleci.com/api/v1.1/project/github/PokeAPI/deploy/build?circle-token=$CIRCLECI_API_TOKEN"


workflows:
  version: 2

  commit:
    jobs:
      - build-and-test-and-deploy:
          filters:
            branches:
              only: master
